name: NoLongGrassExploit
version: 1.0.0
author: damo1995
main: me.damo1995.NLGE.nlge
permissions: 
    nlge.admin: 
        description: gives access to admin stuffs.
commands:
    nlge:
        description: 'General NoLongGrassExplot commands'
        usage: Use /nlge for more info